import { Link } from '../shared/types'

export const extraTools: Link[] = [
  {
    type: 'extra-tool',
    id: 'content-marketplace',
    name: 'Content Marketplace',
    url: 'https://www.semrush.com/marketplace/',
    description: `[Generated] Get quality content written by professional copywriters`,
    tags: ['Content marketing'],
  },
  {
    type: 'extra-tool',
    id: 'content-outline-builder',
    name: 'Content Outline Builder',
    url: 'https://www.semrush.com/outline-builder/',
    status: 'beta',
    description: `[Generated] Create a content brief for your copywriters and editors`,
    tags: ['Content marketing'],
  },
  {
    type: 'extra-tool',
    id: 'impacthero',
    name: 'ImpactHero',
    url: 'https://www.semrush.com/impacthero/',
    description: `[Generated] Create a content brief for your copywriters and editors`,
  },
  {
    type: 'extra-tool',
    id: 'tools-for-amazon',
    name: 'Tools for Amazon',
    url: 'https://lp.sellzone.com/amazon-marketing-tools.html?utm_source=semrush&utm_medium=extratools',
    description: `[Generated] Optimize your Amazon listings and ads`,
  },
  {
    type: 'extra-tool',
    id: 'prowly',
    name: 'Prowly',
    url: 'https://prowly.com/?utm_source=semrush&utm_medium=extratools',
    description: `[Generated] Manage your PR campaigns and build relationships with journalists`,
    tags: ['Social media'],
  },
  {
    type: 'extra-tool',
    id: 'kompyte',
    name: 'Kompyte',
    url: 'https://www.kompyte.com/?utm_source=semrush&utm_medium=extratools',
    description: `[Generated] Track your competitors' marketing strategies`,
    tags: ['Competitive research'],
  },
  {
    type: 'extra-tool',
    id: 'splitsignal',
    name: 'SplitSignal',
    url: 'https://www.semrush.com/splitsignal/',
    status: 'beta',
    description: `[Generated] Test your website's design and content`,
  },
  {
    type: 'extra-tool',
    id: 'custom-reports',
    name: 'Custom reports',
    url: 'https://www.semrush.com/company/custom_report/',
    description: `[Generated] Create custom reports for your clients`,
  },
  {
    type: 'extra-tool',
    id: 'surround-sound',
    name: 'Surround Sound',
    url: 'https://www.semrush.com/srm/',
    description: `Uncover the domains and pages that rank for your keywords, the ones that mention your competition, and those that are mentioning you. Get valuable links and mentions to grow your share of search, whether you rank or not.`,
    tags: ['SEO', 'Competitive research'],
  },
  {
    type: 'extra-tool',
    id: 'pageimprove',
    name: 'PageImprove',
    url: 'https://www.semrush.com/pageimprove/',
    description: `[Generated] Get a prioritized list of issues that are affecting your page's performance in search engines. Fix them to improve your rankings and traffic.`,
  },
]
