import { Link } from './types'

export const menuTools: Link[] = [
  {
    type: 'tool',
    id: 'seo-dashboard',
    name: 'SEO Dashboard',
    url: 'https://www.semrush.com/seo/',
    projectUrl: 'https://www.semrush.com/seo/:projectId',
    description: 'Get a complete overview of your projects SEO performance.',
    tags: ['SEO'],
  },
  {
    type: 'tool',
    id: 'domain-overview',
    name: 'Domain Overview',
    url: 'https://www.semrush.com/analytics/overview/',
    description:
      'Get instant insights into strengths and weaknesses of your competitor or prospective customer.',
    tags: ['SEO', 'Competitve research', 'Advertising', 'Market analysis'],
  },
  {
    type: 'tool',
    id: 'traffic-analytics',
    name: 'Traffic Analytics',
    url: 'https://www.semrush.com/analytics/traffic/overview/',
    description: `Explore competitors’ website traffic stats, discover growth points, and amplify your marketing strategy.`,
    tags: ['SEO', 'Competitve research', '.Trends'],
  },
  {
    type: 'tool',
    id: 'organic-research',
    name: 'Organic Research',
    url: 'https://www.semrush.com/analytics/organic/overview/',
    description: `Do you want to reach the top of the SERP?
Start with learning what works best for your competitors.`,
    tags: ['SEO', 'Competitve research'],
  },
  {
    type: 'tool',
    id: 'keyword-gap',
    name: 'Keyword Gap',
    url: 'https://www.semrush.com/analytics/keywordgap/',
    description: `A tool that helps you compare your keyword profile with your competitors.`,
    tags: ['SEO', 'Competitve research', 'Advertising'],
  },
  {
    type: 'tool',
    id: 'backlink-gap',
    name: 'Backlink Gap',
    url: 'https://www.semrush.com/analytics/gap/backlinks/',
    description: `A tool that helps you compare your backlink profile with your competitors.`,
    tags: ['SEO', 'Competitve research', 'Advertising'],
  },
  {
    type: 'tool',
    id: 'keyword-overview',
    name: 'Keyword Overview',
    url: 'https://www.semrush.com/analytics/keywordoverview/',
    description: `Dive into the largest keyword research database on the market and analyze everything you need to know about a keyword.`,
    tags: ['SEO', 'Keyword research'],
  },
  {
    type: 'tool',
    id: 'keyword-magic-tool',
    name: 'Keyword Magic Tool',
    url: 'https://www.semrush.com/analytics/keywordmagic/',
    description: `Find millions of keyword suggestions for your SEO. `,
    tags: ['SEO', 'Keyword research', 'Advertising'],
  },
  // Generated below
  {
    type: 'tool',
    id: 'keyword-manager',
    name: 'Keyword Manager',
    url: 'https://www.semrush.com/analytics/keywordmanager/',
    description: `[Generated] Manage your keyword lists and track your rankings with the Keyword Manager.`,
    tags: ['SEO', 'Keyword research'],
  },
  {
    type: 'tool',
    id: 'position-tracking',
    name: 'Position Tracking',
    url: 'https://www.semrush.com/position-tracking/',
    description: `[Generated] Track your website’s daily rankings for any keyword in any location and get a complete picture of your website’s ranking performance.`,
    tags: [
      'SEO',
      'Keyword research',
      'Local SEO',
      'Advertising',
      'Ad tracking',
    ],
  },
  {
    type: 'tool',
    id: 'organic-traffic-insights',
    name: 'Organic Traffic Insights',
    url: 'https://www.semrush.com/organic_traffic_insights/',
    description: `[Generated] Get instant insights into the most effective SEO and content strategies used by your competitors.`,
    tags: ['SEO', 'Keyword research'],
  },
  {
    type: 'tool',
    id: 'backlink-analytics',
    name: 'Backlink Analytics',
    url: 'https://www.semrush.com/analytics/backlinks/overview/',
    description: `[Generated] Get a deep dive into your backlink profile and understand how your backlinks impact your SEO performance.`,
    tags: ['SEO', 'Link building'],
  },
  {
    type: 'tool',
    id: 'backlink-audit',
    name: 'Backlink Audit',
    url: 'https://www.semrush.com/backlink_audit/',
    description: `[Generated] Find and remove toxic backlinks to your site with the Backlink Audit tool.`,
    tags: ['SEO', 'Link building'],
  },
  {
    type: 'tool',
    id: 'link-building-tool',
    name: 'Link Building Tool',
    url: 'https://www.semrush.com/link_building/',
    description: `[Generated] Find link-building opportunities, track link-building progress, and analyze incoming links to your site with the Link Building Tool.`,
    tags: ['SEO', 'Link building'],
  },
  {
    type: 'tool',
    id: 'bulk-analysis',
    name: 'Bulk Analysis',
    url: 'https://www.semrush.com/batch/',
    description: `[Generated] Analyze your competitors, find link building opportunities, and export results to XLSX or CSV.`,
    tags: ['SEO', 'Link building'],
  },
  {
    type: 'tool',
    id: 'site-audit',
    name: 'Site Audit',
    url: 'https://www.semrush.com/siteaudit/',
    description: `[Generated] Find and fix technical issues on your website with the Site Audit tool.`,
    tags: ['SEO', 'Technical SEO', 'Local SEO'],
  },
  {
    type: 'tool',
    id: 'listing-management',
    name: 'Listing Management',
    url: 'https://www.semrush.com/listings-management/',
    description: `[Generated] Manage your business listings and reputation across multiple platforms.`,
    tags: ['SEO', 'Technical SEO', 'Local SEO'],
  },
  {
    type: 'tool',
    id: 'seo-content-template',
    name: 'SEO Content Template',
    url: 'https://www.semrush.com/seo-content-template/',
    description: `[Generated] Create SEO-friendly content based on comprehensive research and competitors’ analysis.`,
    tags: ['SEO', 'Technical SEO', 'Content marketing'],
  },
  {
    type: 'tool',
    id: 'on-page-seo-checker',
    name: 'On Page SEO Checker',
    url: 'https://www.semrush.com/on-page-seo-checker/',
    description: `[Generated] Get actionable recommendations based on collected data to improve your website’s SEO performance.`,
    tags: ['SEO', 'Technical SEO', 'Local SEO'],
  },
  {
    type: 'tool',
    id: 'log-file-analyzer',
    name: 'Log File Analyzer',
    url: 'https://www.semrush.com/log-file-analyzer/',
    description: `[Generated] Analyze your log files and get valuable insights into search engine crawling behavior on your website.`,
    tags: ['SEO', 'Technical SEO'],
  },
  {
    type: 'tool',
    id: 'review-management',
    name: 'Review Management',
    url: 'https://www.semrush.com/review-management/',
    description: `[Generated] Manage your online reputation and collect reviews to build trust and increase conversions.`,
    tags: ['Local SEO'],
  },
  {
    type: 'tool',
    id: 'advertising-dashboard',
    name: 'Advertising Dashboard',
    url: 'https://www.semrush.com/ppc/',
    description: `[Generated] Get a complete overview of your PPC performance in one place.`,
    tags: ['Advertising'],
  },
  {
    type: 'tool',
    id: 'advertising-research',
    name: 'Advertising Research',
    url: 'https://www.semrush.com/analytics/adwords/positions/',
    description: `[Generated] Analyze your competitors’ Google Ads campaigns and get insights into your competitors’ PPC strategies.`,
    tags: ['Advertising', 'Market analysis'],
  },
  {
    type: 'tool',
    id: 'display-advertising',
    name: 'Display Advertising',
    url: 'https://www.semrush.com/analytics/da/',
    description: `[Generated] Analyze your competitors’ display ads and get insights into your competitors’ display advertising strategies.`,
    tags: ['Advertising', 'Market analysis'],
  },
  {
    type: 'tool',
    id: 'pla-research',
    name: 'PLA Research',
    url: 'https://www.semrush.com/analytics/pla/positions/',
    description: `[Generated] Analyze your competitors’ Google Shopping campaigns and get insights into your competitors’ PLA strategies.`,
    tags: ['Advertising', 'Market analysis'],
  },
  {
    type: 'tool',
    id: 'ppc-keyword-tool',
    name: 'PPC Keyword Tool',
    url: 'https://www.semrush.com/keyword-tool/',
    description: `[Generated] Find the right keywords for your Google Ads campaigns with the PPC Keyword Tool.`,
    tags: ['Advertising', 'Keyword research'],
  },
  {
    type: 'tool',
    id: 'ads-history',
    name: 'Ads History',
    url: 'https://www.semrush.com/analytics/phrase/',
    description: `[Generated] Analyze your competitors’ Google Ads campaigns and get insights into your competitors’ PPC strategies.`,
    tags: ['Advertising', 'Keyword research'],
  },
  {
    type: 'tool',
    id: 'social-dashboard',
    name: 'Social Dashboard',
    url: 'https://www.semrush.com/social-media/',
    description: `[Generated] Get a complete overview of your social media performance in one place.`,
    tags: ['Social media'],
  },
  {
    type: 'tool',
    id: 'social-poster',
    name: 'Social Poster',
    url: 'https://www.semrush.com/social-media/?tool=poster',
    description: `[Generated] Schedule and post content to your social media accounts.`,
    tags: ['Social media'],
  },
  {
    type: 'tool',
    id: 'social-tracker',
    name: 'Social Tracker',
    url: 'https://www.semrush.com/social-media/?tool=tracker',
    description: `[Generated] Track your social media performance and compare it to your competitors’ performance.`,
    tags: ['Social media'],
  },
  {
    type: 'tool',
    id: 'social-analytics',
    name: 'Social Analytics',
    url: 'https://www.semrush.com/social-media/?tool=analytics',
    description: `[Generated] Analyze your social media performance and compare it to your competitors’ performance.`,
    tags: ['Social media'],
  },
  {
    type: 'tool',
    id: 'social-inbox',
    name: 'Social Inbox',
    url: 'https://www.semrush.com/social-media/?tool=inbox',
    status: 'beta',
    description: `[Generated] Manage all your social media messages in one place.`,
    tags: ['Social media'],
  },
  // {
  //   type: 'tool',
  //   id: 'influencer-analytics',
  //   name: 'Influencer Analytics',
  //   url: 'https://www.semrush.com/apps/buzzguru-influencer-marketing-platform/',
  // },
  {
    type: 'tool',
    id: 'get-started',
    name: 'Get Started',
    url: 'https://www.semrush.com/content-marketing/get-started/',
    description: `[Generated] Get started with Content Marketing Toolkit.`,
    tags: ['Content marketing'],
  },
  {
    type: 'tool',
    id: 'topic-research',
    name: 'Topic Research',
    url: 'https://www.semrush.com/topic-research/',
    description: `[Generated] Find the most popular content around the topic of your choice.`,
    tags: ['Content marketing'],
  },
  {
    type: 'tool',
    id: 'seo-writing-assistant',
    name: 'SEO Writing Assistant',
    url: 'https://www.semrush.com/swa/',
    description: `[Generated] Write SEO-friendly content with the SEO Writing Assistant.`,
    tags: ['Content marketing'],
  },
  {
    type: 'tool',
    id: 'brand-monitoring',
    name: 'Brand Monitoring',
    url: 'https://www.semrush.com/mentions/',
    description: `[Generated] Monitor your brand’s online presence and get insights into your competitors’ strategies.`,
    tags: ['Content marketing'],
  },
  {
    type: 'tool',
    id: 'contentshake',
    name: 'ContentShake',
    url: 'https://www.semrush.com/app/contentshake/',
    status: 'new',
    description: `[Generated] Get content ideas for your blog and create high-quality content with ContentShake.`,
    tags: ['Content marketing'],
  },
  {
    type: 'tool',
    id: 'post-tracking',
    name: 'Post Tracking',
    url: 'https://www.semrush.com/post-tracking/',
    description: `[Generated] Track the performance of your articles and get insights into your competitors’ strategies.`,
    tags: ['Content marketing'],
  },
  {
    type: 'tool',
    id: 'content-audit',
    name: 'Content Audit',
    url: 'https://www.semrush.com/content-audit/',
    description: `[Generated] Audit your content and get insights into your competitors’ strategies.`,
    tags: ['Content marketing'],
  },
  {
    type: 'tool',
    id: 'market-explorer',
    name: 'Market Explorer',
    url: 'https://www.semrush.com/market-explorer/overview/',
    description: `[Generated] Analyze your market and get insights into your competitors’ strategies.`,
    tags: ['.Trends'],
  },
  {
    type: 'tool',
    id: 'eyeon',
    name: 'EyeOn',
    url: 'https://www.semrush.com/eyeon-monitoring/',
    description: `[Generated] Monitor your competitors’ online activities and get insights into their strategies.`,
    tags: ['.Trends'],
  },
  {
    type: 'tool',
    id: 'one2target',
    name: 'One2Target',
    url: 'https://www.semrush.com/analytics/one2target/demographics/',
    description: `[Generated] Analyze your target audience and get insights into your competitors’ strategies.`,
    tags: ['.Trends'],
  },
  {
    type: 'tool',
    id: 'agency-partners',
    name: 'Agency Partners',
    url: 'https://www.semrush.com/agencies/landing/',
    description: `[Generated] Get more clients and grow your agency with SEMrush.`,
    tags: ['Agency solutions', 'Lead generation'],
  },
  {
    type: 'tool',
    id: 'lead-finder',
    name: 'Lead Finder',
    url: 'https://www.semrush.com/lead-finder/',
    description: `[Generated] Find leads for your agency and grow your business.`,
    tags: ['Agency solutions', 'Lead generation'],
  },
  {
    type: 'tool',
    id: 'bid-finder',
    name: 'Bid Finder',
    url: 'https://www.semrush.com/bid-finder/landing/',
    status: 'beta',
    description: `[Generated] Find leads for your agency and grow your business.`,
    tags: ['Agency solutions', 'Lead generation'],
  },
  {
    type: 'tool',
    id: 'client-portal',
    name: 'Client Portal',
    url: 'https://www.semrush.com/my-insights/dashboard',
    description: `[Generated] Share your SEMrush data with your clients.`,
    tags: ['Agency solutions', 'Optimization and automation'],
  },
  {
    type: 'tool',
    id: 'crm',
    name: 'CRM',
    url: 'https://www.semrush.com/crm/',
    description: `[Generated] Manage your leads and clients with SEMrush.`,
    tags: ['Agency solutions', 'Optimization and automation'],
  },
  {
    type: 'tool',
    id: 'my-reports',
    name: 'My Reports',
    url: 'https://www.semrush.com/my_reports/grid/',
    description: `[Generated] Create custom reports for your clients.`,
    tags: ['Agency solutions', 'Optimization and automation', 'Management'],
  },
  {
    type: 'tool',
    id: 'user-management',
    name: 'User Management',
    url: 'https://www.semrush.com/corporate/account',
    description: `[Generated] Manage your team’s access to Semrush.`,
    tags: ['Management'],
  },
  {
    type: 'tool',
    id: 'marketing-calendar',
    name: 'Marketing Calendar',
    url: 'https://www.semrush.com/calendar/',
    description: `[Generated] Plan and manage your marketing campaigns.`,
    tags: ['Management'],
  },
  {
    type: 'tool',
    id: 'notes',
    name: 'Notes',
    url: 'https://www.semrush.com/notes/',
    description: `[Generated] Take notes and share them with your team.`,
    tags: ['Management'],
  },
]
